parameters:
    # Adds a fallback DATABASE_URL if the env var is not set.
    # This allows you to run cache:warmup even if your
    # environment variables are not available yet.
    # You should not need to change this value.
    env(DATABASE_URL): ''

doctrine:
    dbal:
        default_connection: master
        types:
            SimulationStatusId:
                class: App\Infrastructure\Doctrine\Domain\Model\Entities\DoctrineSimulationStatusId
                commented: true

        connections:
            master:
                url: '%env(resolve:MASTER_DATABASE_URL)%'
                charset:  UTF8

            slave:
                url: '%env(resolve:SLAVE_DATABASE_URL)%'
                charset:  UTF8

    orm:
        auto_generate_proxy_classes: '%kernel.debug%'

        default_entity_manager: master
        entity_managers:
            master:
                connection: master
                naming_strategy: doctrine.orm.naming_strategy.underscore
                auto_mapping: true
                mappings:
                    App:
                        is_bundle: false
                        type: xml
                        dir: '%kernel.project_dir%/src/Infrastructure/Doctrine/Domain/Model/Entities'
                        prefix: 'App\Domain\Model\Entities'
                        alias: App
            slave:
                connection: slave
                naming_strategy: doctrine.orm.naming_strategy.underscore
                mappings:
                    App:
                        is_bundle: false
                        type: xml
                        dir: '%kernel.project_dir%/src/Infrastructure/Doctrine/Domain/Model/Entities'
                        prefix: 'App\Domain\Model\Entities'
                        alias: App