version: '3'

services:

  # container usage:
  #  docker-compose run testing /var/www/vendor/bin/phpunit
  cli:
    build: docker/php-cli
    working_dir: /var/www/
    ports:
      - 9090:9090
    volumes:
      - .:/var/www

  # container usage:
  #  docker-compose run composer [command]
  composer:
    build: docker/composer
    working_dir: /var/www/
    volumes:
      - .:/var/www
    command: -q
